language: node_js

node_js:
  - 6.0.0

# establish environment variables here
env:
  global:
    - GH_USER_NAME="conor123"
    - GH_USER_EMAIL="conor@conorryan.ie"
    - GH_REPO="conor123/terraform-example"
    - secure: "tZD5NUJLBc5QddbmXVVnWxHq4ryULC/7QscONPxu7a65MCRgZfCvBqE0tZKVSiZw/RppC3NFYwmqNPlEk1O9wgd2vmMFSm85JgVzTwemohIjuTCA6/WXf7bKCD4lZUaEGzGsw6sUnVQCJ7QJ0bxABUiMs2uSaNk42FzwYIy8rIfRGsZ4+gvSfBHzyxQf8Wi4FM4BJOhwx8vd3BZEP0ZttwGlm0T5N7ZLmZmNY9Eei5QIwF45h90al9nRUQYMWH1PUn2nuW+eusmwQTgM0lBUJbqLDFpg2+DOb2LBFe69zewrXg36f6zjhjTUdLOBYr+pgnK3dEg3mkJhB30MFfrL7bDkrDK6WlNzqxRZWAszhAzbBadcCw6OnbXtxPVvqI4KWKg/2V9wxbJCTSBp3GK1DM3wVzT1PorOpt5AWR6VhLdsJirNO/RhEGzP4TA9a8PAp3k5kBoru2MLtGO+inA2SIwC4jQRdHw0SnF8k+VbAVR6FB8avY0AhHUYI8n/i7PYfOy8nkaBxEk72Zw75vbwo3hizqDJj75R4llTaocTzOoSBMlu9Gb0xlPh7sGsqtLrq3pHhrLdJiv5xOtbem32yd6gHeQwbdl93OD8NNN+wu5Zkm58gxICuqMAiQ84mXi8esz32Cv2FKARB4WoQZoVR/Kt6B8hjbFk321PB/Vh3z8="

# install ruby sass/compass for use by gulp-node-sass
before_install:
  - gem install sass -v 3.4.22
  - gem install compass -v 1.0.3

install:
  - npm install

script:
  - npm run build

# install terraform
before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# terraform apply
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: conor123/terraform-example
      branch: master
