language: node_js

node_js:
  - 6.0.0

# establish environment variables here
env:
  global:
    - GH_USER_NAME="conor123"
    - GH_USER_EMAIL="conor@conorryan.ie"
    - GH_REPO="conor123/terraform-example"
    - secure: "53uP/TjjAFz3lVyw8lhJSbjBm/qoViF4z4vW3lerAn9kjgiZAZ2NrggqBsvjgeMCH0MAc6oW9SI8HdYowOIGeg6vTXr75e83lCkEiZEZ7MomaocmZ1YbHjoGyzdblDAO45BaC3SwckBz5dQq8DbQC62ctSRduI3x7yV08z0gou7uyHyqzt6CWMOKZAMuiZ6sAWavvrBfWzrYknopmbmVoVjb0gZw9qTGsA+srH2/vZhfgqPptedcUwfea3arbLL8Ai2S9GkajjMNBX/UA55u0sk8wzdCvhF60Ah2WOWx/ssiZh3AZuW0vqJqvzdTU9UbAGH59zZTYxF/ohsXY5sT2BsmwXTnRQw/P+ScW32X7MVNn3myTGH92B9g+IT63wdUzZMutfjYLAm3RfhucmR6URuepPBFTYHO8es4ItTFMjtRxPM082pjYUGe+QYtDhDonSW2cck5KoK9jAdMnNpTFOnlFWw7eNrAI7XWFeTdN7O6vdEmCrL/xAClOkj9IqKyvUgyLmKqzxZ/gWTLUcrmAgGRb7/VdCRskxoz8ss0zaAgr767YP3aInNk8Se8oYTRt6UuJ2IswvDbFtqnSOB0Mb3qfyI3xCYrkXagGykA+f/mGvnPzP+ow9lXJMYSslvZTg7vVav4uNSykRjnrhw5LZESrclmfO8ogRzMT+udc1s="

# install ruby sass/compass for use by gulp-node-sass
before_install:
  - gem install sass -v 3.4.22
  - gem install compass -v 1.0.3

install:
  - npm install

script:
  - npm run build

# install terraform
before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# terraform apply
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: conor123/terraform-example
      branch: master
